# Speed Controls
d set speed 1 ; show-text "Speed: 1x"
a add speed 0.01 ; show-text "Speed: ${speed}x"
s add speed -0.01 ; show-text "Speed: ${speed}x"

# Mouse Controls
MBTN_MID cycle fullscreen
MBTN_RIGHT cycle pause
WHEEL_UP   add speed 0.01 ; show-text "Speed: ${speed}x"
WHEEL_DOWN add speed -0.01 ; show-text "Speed: ${speed}x"

# Seeking (5 Seconds)
z seek -5
x seek 5
LEFT seek -5
RIGHT seek 5
